### ISSUE TITLE
Addline Tria.ge domain

### ISSUE THREAD

**Issue by kh4rdur** [scottpas/assemblyline-service-triage-sandbox#5]
Links to tria.ge are being used in the Assemblyline result when using the different url's for private or public Triage environment.

Line 182 and line 188 of the service.py module use a static domain for showing the result location/Tasksession url. 
These could be changed to use root_url you use to connect to the server.

**Comment by scottpas** [comment]
Hi @kh4rdur
Thanks for flagging this! I've merged in the change to address this. Please let me know if that works for you.

**Comment by kh4rdur** [comment]
Sorry for the late Reply! Works great!
